/* Author: Green Apple
 * Date Created: August 12, 2025
 * 
 * Notes: 
 */

package net.greenapple.arrestwt.util

// ====== IMPORTS ======
import net.greenapple.arrestwt.data.type.TagData
import android.content.Context
import android.util.Log
import kotlinx.serialization.json.Json
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.SerializationException
import java.io.IOException
import java.security.MessageDigest
import androidx.compose.ui.graphics.Color

// ====== TAG UTILS ======
object TagUtils {

  /* ====== Return a Color Generated by Id 
   * Ensures an id gives the same default color on all instances */
  fun createColorFromId(
    id:         String,
    saturation: Float   = 0.55f,
    lightness:  Float   = 0.50f
  ): Color {

    val lowerId = id.lowercase().trim()

    /* --- Get hash of Id */
    val hash    = MessageDigest.getInstance("SHA-1")
      .digest(lowerId.toByteArray(Charsets.UTF_8))

    /* --- Get hue */
    val n       = (hash[0].toUByte().toInt() shl 16)  or
                  (hash[1].toUByte().toInt() shl 8)   or
                  hash[2].toUByte().toInt()
    val hue     = (n % 360).toFloat()

    /* --- Get color */
    return Color.hsl(
      hue         = hue,
      saturation  = saturation.coerceIn(0f, 1f),
      lightness   = lightness.coerceIn(0f, 1f),
      alpha       = 1f
    )
  }

  /* ====== Return Tag From JSON */
  fun loadTagFromJson(
    context:  Context,
    id:       String
  ): TagData? {

    /* === Try to Laod JSON String From File */
    return try {
      val jsonStr = context.assets
        .open("user/tags/$id.tag.json")
        .bufferedReader()
        .use {
          it.readText()
        }

      Json.decodeFromString<TagData>(jsonStr)

    } catch (e: IOException) {
      Log.e("TagUtils", "I/O Exception on $id")
      e.printStackTrace()
      null
    } catch (e: SerializationException) {
      Log.e("TagUtils", "Serialization Exception on $id")
      e.printStackTrace()
      null
    }
  }

  /* ====== Return Tag From JSON or Placeholder */
  fun loadTagFromJsonOrDefualt(
    context:  Context,
    id:       String
  ): TagData {

    /* --- Try to load tag */
    val tag = loadTagFromJson(
      context = context,
      id      = id
    )

    /* --- Return tag if there is one */
    return if (tag != null) {
      tag

    /* --- Return placeholder tag otherwise */
    } else {
      TagData(
        id    = id,
        name  = id
      )
    }
  }
}